### ISSUE TITLE
Tag current version

### ISSUE THREAD

**Issue by jb-reynaud** [octopush/OctopushSMSBundle#4]
Hi, is it possible to tag a release please? at least 0.1.0

**Comment by octopush** [comment]
Hi,
Yes, what would you like to do specificly ?

**Comment by jb-reynaud** [comment]
Hi, I would like to use your bundle on my project. In composer json, I know and use
```json
"octopush/sms-bundle": "dev-master"
```
BUT it will be secure if your tag a version to do something like
```json
"octopush/sms-bundle": "^1.0.0"
```
In case if tomorrow you add more commit, It will not break on a composer update.

So if you can make a release [here](https://github.com/octopush/OctopushSMSBundle/releases) it will be great

**Comment by octopush** [comment]
I think you are write.
Would you like to propose your own release ?

Best regards

**Comment by jb-reynaud** [comment]
We would like to have a version `v1.0.0` please. Can you do it [here](https://github.com/octopush/OctopushSMSBundle/releases) we don't have the right.

Thank you!

**Comment by octopush** [comment]
Done.
Tel me if everything's at you convenience.
