### ISSUE TITLE
Missing quotes in services configuration

### ISSUE THREAD

**Issue by Thomson2306** [octopush/OctopushSMSBundle#5]
Hi,

Since Symfony 3, you're supposed to add quotes around scalar values in the services.yml. It actually throws a deprecation waring in the Symfony profiler :

Not quoting the scalar "%octopush_sms.api_key%" starting with the "%" indicator character is deprecated since Symfony 3.1 and will throw a ParseException in 4.0 in vendor/octopush/sms-bundle/DependencyInjection/../Resources/config/services.yml.

The fix is quite easy, simply add quotes around %octopush_sms.user_login% and %octopush_sms.api_key% in the services.yml :

`- '%octopush_sms.user_login%'`
`- '%octopush_sms.api_key%'`

Thanks !
Thomas

**Comment by octopush** [comment]
Thanks for your notification.
I'll have it added on the repo.

Regards

**Comment by Thomson2306** [comment]
Hello,

Thanks for the quick update :) Would it be possible to update the project on Packagist ? (A composer update doesn't show any difference currently)

Thanks a lot,
Best regards,
Thomas

**Comment by octopush** [comment]
Bundle has just been updated on Packagist.
It should have been done automaticly, but anyway, it has been done manually.

Thanks for your following !

**Comment by Thomson2306** [comment]
Perfect, everything is good right now. Thanks for the quick support !
Best regards, and merry christmas :)
Thomas
